### ISSUE TITLE
Make a requirements file

### ISSUE THREAD

**Issue by bsoyka** [bsoyka/stem-bot#1]
Create a simple requirements.txt file using exact versions.

For example, `discord.py`'s latest version is 1.3.3, so you'd add:
```
discord.py==1.3.3
```

Repeat this for all the dependencies found in the project.

One exception is for the `wikipedia` module:
```
wikipedia @ git+git://github.com/goldsmith/Wikipedia.git@2065c568502b19b8634241b47fd96930d1bf948d
```
This is to fix an issue with BeautifulSoup parsing in the `wikipedia` module currently on PyPI. (goldsmith/Wikipedia#107)

**Comment by JasonG-FR** [comment]
You might want to check [pipenv](https://github.com/pypa/pipenv), it's a great tool that does what you want to do automatically: 

> It automatically creates and manages a virtualenv for your projects, as well as adds/removes packages from your Pipfile as you install/uninstall packages. It also generates the ever-important Pipfile.lock, which is used to produce deterministic builds.

You'd only need to initially set-up your virtual environment, install your dependencies and pipenv will automatically generate a Pipfile (very similar to a requirements.txt) and a Pipfile.lock containing the hashes of the dependencies installed.

**Comment by bsoyka** [comment]
@JasonG-FR Thanks for the suggestion! I wasn’t really even thinking about using pipenv for this since the project is so small, but now that I think about it, it may be beneficial anyways. Closing now!
